### ISSUE TITLE
Sculk Transmitter Shulker Box Dupe.

### ISSUE THREAD

**Issue by ChrisR-25** [KyaniteMods/DeeperAndDarker#274]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Dupe glitch, with Sculk Transmitter and Shulker Box
If a Shulker Box is broken while a player is using a Sculk Transmitter access it, the inventory is not closed and items, that now are within the broken shulker, can be removed from the non existent inventory. 

**To Reproduce**:
1. Open a Shulker Box with a Sculk Transmitter.
2. Break the Shulker Box
3. Remove any items from the box.
4. Place the dropped Shulker Box
5. You now have duped the item.

**Comment by NewJumper** [comment]
confirmed. this happens because the transmitter isn't constantly checking if the block exists or not. it only checks when opening the transmitter.
there are two possible fixes:
- make shulker boxes not supported with transmitters
- find a way to continuously check if the block exists while using the transmitter

**Comment by NewJumper** [comment]
is this an issue for fabric?

**Comment by NewJumper** [comment]
fixed for forge in d32baa2751f4b577f3b8a19dbab44e6bede90e88

**Comment by Pedro270707** [comment]
Fixed on Fabric
