### ISSUE TITLE
Parsing error loading recipe with Forge Recipe on Fabric

### ISSUE THREAD

**Issue by suerion** [KyaniteMods/DeeperAndDarker#374]
**Minecraft Version**: 1.21.1
**Mod Version**: deeperdarker-fabric-1.21-1.3.2.1
**Mod Loader**: fabric

**Description**:
A lot of Forge Mod Receipes will be loading in Fabric, it is only an Log error, but should be fixed in Future
(Mekanism etc)

**To Reproduce**:
Only Start Server see at log

**Additional context**:
https://mclo.gs/cX8M9H0

**Comment by Nova-Katt** [comment]
My logs are smacked with this aswell, easily taking up 95% of the entire log.

The recipes provided by Deeper And Darker is for the Mekanism which I'm not using.

The mod author hasn't used conditional recipe loading to check if Mekanism is installed, therefore a heckton of errors.

They have also put them in the Mekanism namespace instead of the one for this mod mod, so it's tricky to see which mod is causing the problem unless you happen to notice the references to gloomslate, sculk-stone, and so on.

I hope they can fix that soon.

**Comment by Pedro270707** [comment]
Fixed https://github.com/KyaniteMods/DeeperAndDarker/commit/aaef98a38f466d5539dbf5365ece5cd65d12d01e
