### ISSUE TITLE
Resonarium armors does not have a texture

### ISSUE THREAD

**Issue by JustBilBeary** [KyaniteMods/DeeperAndDarker#381]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2.1
**Mod Loader**: fabric

**Description**:
Resonarium armors shows purple and black on player, but textures in inventory is fine.

![Screenshot 2024-10-23 151614](https://github.com/user-attachments/assets/7dc278e3-5212-43bb-a0e9-13d299cb162d)

**Additional context**:
I'm using plethora of mods, if needed I can send an export of my modpack

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/980f881d-ca23-4746-90c2-b0aa90a94639)
Same here!

**Comment by galenvares** [comment]
I've looked at this issue and it appears to be a problem related to not having updated the resonarium armor resource path in the code after changing the model texture path. 

The code still references the original minecraft/textures instead of the deeperdarker/textures folder when declaring the model texture path.

The guilty commit appears to be this one:

https://github.com/KyaniteMods/DeeperAndDarker/commit/4b94c9f89d1e51496eade0455d16608b5420daf2

As a user, you can "fix" this with this simple texture pack that I made that just adds the textures back where they originally were, just as the source code needs:

[ResonariumFIX.zip](https://github.com/user-attachments/files/17811991/ResonariumFIX.zip)

**Comment by Pedro270707** [comment]
Fixed https://github.com/KyaniteMods/DeeperAndDarker/commit/6003ba5253eaa02d51a3304b801d8459e98dfb2d
